void init();
void nextChar();
void error(char *fmt, ...);
void fatal(char *fmt, ...);
void expected(char *fmt, ...);
void match(char c);
char getName();
char getNum();
void emit(char *fmt, ...);
void prog();
void prolog();
void epilog(char name);
void doblock(char name);
void declarations();
void labels();
void constants();
void types();
void variables();
void doprocedure();
void dofunction();
void getclass();
void gettype();
void topdecl();
void dofunc(char name);
void dodata(char name);