void init();
void nextChar();
void error(char *fmt, ...);
void fatal(char *fmt, ...);
void expected(char *fmt, ...);
void skipWhite();
void match(char c);
char getName();
int getNum();
void emit(char *fmt, ...);
int isAddOp(char c);
void ident();
int factor();
void multiply();
void divide();
int term();
void add();
void subtract();
int expression();
void assignment();
